version: '3'
services:
  sync:
    depends_on:
      - dird
    environment:
      TARGETS: ""
  dird:
    volumes:
      - "./etc/wazo-dird/conf.d/asset.no-ssl-private-key.yml:/etc/wazo-dird/conf.d/20-config.yml"
      - "./ssl/dird/server.crt:/tmp/ssl/dird/server.crt"
