version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - db
      # - confd  # not confd, we WANT it to take time to start
    environment:
      PORTS: "dird:9489 auth:9497 db:5432"
  dird:
    depends_on:
      - america
    volumes:
      - "./etc/wazo-dird/conf.d/asset.wazo_users_late_confd.yml:/etc/wazo-dird/config.yml"
  america:
    image: python:2.7.16-buster
    volumes:
      - "./confd_data/asset.wazo_users_late_confd:/tmp"
    command: /tmp/run_confd
