version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - microsoft-mock
      - db
      - rabbitmq
    environment:
      TARGETS: "auth:9497 dird:9489 microsoft-mock:80 db:5432 rabbitmq:5672"
