version: '3'
services:
  sync:
    depends_on:
      - auth
      - confd
    environment:
      TARGETS: "confd:9486 auth:9497"
  confd:
    image: python:2.7.16-buster
    volumes:
      - "./confd_data/asset.wazo_users:/tmp"
    ports:
      - "9486"
    command: /tmp/run_confd
